### PR TITLE
dev: standardization of the integration of formatters

### LINKED ISSUE #362: Maybe inline diff tool into golangci-lint
Got a few issues that "diff" isn't installed, especially on windows. We can inline it's code into golangci-lint

### LINKED ISSUE #3408: Errors during golangci operation
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc.).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

I am using the last version golangco 1.50.1 on local maschine (windows). 
When I try to perform linter, I get following errors: 
```
level=warning msg="[runner] Can't run linter goanalysis_metalinter: gci: 4:12: expected ';', found \"testing\" (and 3 more errors)"
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: gci: 4:12: expected ';', found \"testing\" (and 3 more errors)\n\n"
```

What can they be related to?
How can I fix them?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```
1.50.1
</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```
```yml
run:
  tests: true
  build-tags:
    - bench
    - !bench

linters-settings:
  funlen:
    lines: 150
    statements: 80

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
```
windows
</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v

level=info msg="[config_reader] Config search paths: [./ C:\\Users\\divanov\\Desktop\\GO\\otus_go_homework C:\\Users\\divanov\\Desktop\\GO C:\\Users\\divanov\\Desktop C:\\Users\\divanov C:\\Users C:\\ C:\\Users\\divanov\\go]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 47 linters: [asciicheck bodyclose depguard dogsled dupl durationcheck errorlint exhaustive exportloopref funlen gci gocognit goconst gocritic gocyclo godot gofmt gofumpt goheader goprintffuncname gosec gosimple govet importas ineffassign lll makezero misspell nestif nilerr noctx nolintlint prealloc predeclared revive rowserrcheck sqlclosecheck staticcheck stylecheck tagliatelle thelper typecheck unconvert unparam unused wastedassign whitespace]"
level=info msg="[loader] Using build tags: [bench ]"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|deps|files|imports|exports_file|name|types_sizes) took 243.6534ms"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 0s"
level=info msg="[linters_context] importas settings found, but no aliases listed. List aliases under alias: key."
level=error msg="[linters_context] typechecking error: pattern ./...: directory prefix . does not contain modules listed in go.work or their selected dependencies"
level=info msg="[linters_context/goanalysis] analyzers took 6.9762ms with top 10 stages: buildir: 4.9827ms, fact_deprecated: 1.9935ms, cgocall: 0s, ST1020: 0s, gosec: 0s, SA5002: 0s, SA6001: 0s, exportloopref: 0s, printf: 0s, SA1029: 0s"
level=info msg="[runner] processing took 0s with stages: exclude-rules: 0s, nolint: 0s, max_per_file_from_linter: 0s, severity-rules: 0s, path_prefixer: 0s, sort_results: 0s, filename_unadjuster: 0s, path_prettifier: 0s, skip_dirs: 0s, diff: 0s, max_same_issues: 0s, max_from_linter: 0s, autogenerated_exclude: 0s, exclude: 0s, uniq_by_line: 0s, source_code: 0s, path_shortener: 0s, cgo: 0s, skip_files: 0s, identifier_marker: 0s"
level=info msg="[runner] linters took 1.0423697s with stages: goanalysis_metalinter: 1.041954s"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 15 samples, avg is 46.3MB, max is 56.9MB"
level=info msg="Execution took 1.3529325s"
```

</details>

### Code example or link to a public repository

<details>

```go
// add your code here
```
</details>

### PR DESCRIPTION
**Pull request by ldez**
This standardizes the integration of formatters.

Side effect:
- the package `github.com/golangci/gofmt/goimports` from the module `github.com/golangci/gofmt` is removed :tada:
- the `diff` binary is not used anymore :tada: :tada:

Closes #3408
Closes #362

Other issues related to the usage of `diff` (on Windows):
- #4867
- #4276
- #2021
- #1169
- #307

Related to #5296

### CODE REVIEW

**Comment by StevenACoffman** [comment]
This is wonderful! Is there a cli flag or something to run just the set of formatters prior to all other linters? While gci, gofumpt are 100% reliable, we have found that the suggested fixes for some linters are less reliable.

We don't bother to review formatter fixes, but we do want a human to check suggested fixes from other linters.

**Comment by ldez** [comment]
@StevenACoffman Take a look to https://github.com/golangci/golangci-lint/issues/5296

File: pkg/goformatters/analyzer.go [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+)
+
+// NewAnalyzer converts a [Formatter] to an [analysis.Analyzer].
+func NewAnalyzer(logger logutils.Log, doc string, formatter Formatter) *analysis.Analyzer {
+	return &analysis.Analyzer{
+		Name: formatter.Name(),
+		Doc:  doc,
+		Run: func(pass *analysis.Pass) (any, error) {
+			for _, file := range pass.Files {
+				position, isGoFiles := goanalysis.GetGoFilePosition(pass, file)
```
Comment (alexandear) [inline pkg/goformatters/analyzer.go:24]: Perhaps should be without `s`:
```suggestion
				position, isGoFile := goanalysis.GetGoFilePosition(pass, file)
```

File: pkg/goformatters/internal/commons.go [hunk 2]
```diff
@@ -0,0 +1,6 @@
+package internal
+
+import "github.com/golangci/golangci-lint/pkg/logutils"
+
+// FormatterLogger must be use only when the context logger is not available.
```
Comment (alexandear) [inline pkg/goformatters/internal/commons.go:5]:
```suggestion
// FormatterLogger must be used only when the context logger is not available.
```
