### PR TITLE
fix: filter invalid issues before other processors

### LINKED ISSUE #4550: Upgraded to 1.57.0, all my "nolint" comments are not working (contextcheck)
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

Upgraded my golangci-lint via brew to the latest version. I use this in 20+ projects and have used it for a long time. After upgrading and running, several nolint directives are not working.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 1.57.0 built with go1.22.1 from ddc703d on 2024-03-19T22:57:15Z
```

</details>

### Configuration

<details>

```console
# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # default concurrency is an available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 6m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # include test files or not, default is true
  tests: true

  # list of build tags, all linters use it. Default is empty list.
  build-tags:
    - mytag

  # which dirs to skip: issues from them won't be reported;
  # can use regexp here: generated.*, regexp is applied on full path;
  # default value is empty list, but default dirs are skipped independently
  # of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-dirs:
    - .github
    - .make
    - dist

  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true

  # which files to skip: they will be analyzed, but issues from them
  # won't be reported. Default value is empty list, but there is
  # no need to include all autogenerated files, we confidently recognize
  # autogenerated files. If it's not please let us know.
  # "/" will be replaced by current OS file path separator to properly work
  # on Windows.
  skip-files:
    - ".*\\.my\\.go$"
    - lib/bad.go

  # by default isn't set. If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #modules-download-mode: readonly|release|vendor

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false


# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

  # make issues output unique by line, default is true
  uniq-by-line: true

  # add a prefix to the output file references; default is no prefix
  path-prefix: ""


# all available settings of specific linters
linters-settings:
  dogsled:
    # checks assignments with too many blank identifiers; default is 2
    max-blank-identifiers: 2
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 100
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false

    # [deprecated] comma-separated list of pairs of the form pkg:regex
    # the regex is used to ignore names within pkg. (default "fmt:.*").
    # see https://github.com/kisielk/errcheck#the-deprecated-method for details
    ignore: fmt:.*,io/ioutil:^Read.*

    # path to a file containing a list of functions to exclude from checking
    # see https://github.com/kisielk/errcheck#excluding-functions for details
    #exclude: /path/to/file.txt
  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: false
  funlen:
    lines: 60
    statements: 40
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only support one prefix
    # if not set, use goimports.local-prefixes
    local-prefixes: github.com/org/project
  gocognit:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 4
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 3
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 10
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    #enabled-checks:
    #  - rangeValCopy

    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance
    disabled-tags:
      - experimental

    settings: # settings passed to gocritic
      captLocal: # must be valid enabled check name
        paramsOnly: true
      rangeValCopy:
        sizeThreshold: 32
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 10
  godot:
    # check all top-level comments, not only declarations
    check-all: false
  godox:
    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging
    keywords: # default keywords are TODO, BUG, and FIXME, these can be overwritten by this setting
      - NOTE
      - OPTIMIZE # marks code that should be optimized before merging
      - HACK # marks hack-arounds that should be removed before merging
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goheader:
    values:
      const:
      # define here const type values in format k:v, for example:
      # YEAR: 2020
      # COMPANY: MY COMPANY
      regexp:
      # define here regexp type values, for example
      # AUTHOR: .*@mycompany\.com
    template:
      ""
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/org/project
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gomnd:
    settings:
      mnd:
        # the list of enabled checks, see https://github.com/tommy-muehle/go-mnd/#checks for description.
        checks: [argument,case,condition,operation,return,assign]
  govet:
    # report about shadowed variables
    check-shadowing: true

    # settings per analyzer
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    # enable or disable analyzers by name
    enable:
      - atomicalign
    enable-all: false
    #disable:
      #- shadow
    disable-all: false
  #depguard:
  #  list-type: blacklist
  #  include-go-root: false
  #  packages:
  #    - github.com/sirupsen/logrus
  #  packages-with-error-message:
  #    # specify an error message to output when a blacklisted package is used
  #    - github.com/sirupsen/logrus: "logging is allowed only by logutils.Log"
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - bsv
      - bitcoin
  nakedret:
    # make an issue if func has more lines of code than this setting, and it has naked returns; default is 30
    max-func-lines: 30
  prealloc:
    # XXX: we don't recommend using this linter before doing performance profiling.
    # For most programs usage of prealloc will be a premature optimization.

    # Report preallocation suggestions only on simple loops that have no returns/breaks/continues/gotos in them.
    # True by default.
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  nolintlint:
    # Enable to ensure that nolint directives are all used. Default is true.
    allow-unused: false
    # Disable to ensure that nolint directives don't have a leading space. Default is true.
    #allow-leading-space: true
    # Exclude following linters from requiring an explanation.  Default is [].
    allow-no-explanation: []
    # Enable to require an explanation of nonzero length after each nolint directive. Default is false.
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed. Default is false.
    require-specific: true
  rowserrcheck:
    packages:
      - github.com/jmoiron/sqlx
  testpackage:
    # regexp pattern to skip files
    skip-regexp: (export|internal)_test\.go
  unparam:
    # Inspect exported functions, default is false. Set to true if no external program/library imports your code.
    # XXX: if you enable this setting, unparam will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find external interfaces. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    check-exported: false
  unused:
    # treat code as a program (not a library) and report unused exported identifiers; default is false.
    # XXX: if you enable this setting, unused will report a lot of false-positives in text editors:
    # if it's called for subdir of a project it can't find funcs usages. All text editor integrations
    # with golangci-lint call it on a directory with the changed file.
    #check-exported: false
  whitespace:
    multi-if: false   # Enforces newlines (or comments) after every multi-line if statement
    multi-func: false # Enforces newlines (or comments) after every multi-line function signature
  wsl:
    # If true append is only allowed to be cuddled if appending value is
    # matching variables, fields or types on the line above. Default is true.
    strict-append: true
    # Allow calls and assignments to be cuddled as long as the lines have any
    # matching variables, fields or types. Default is true.
    allow-assign-and-call: true
    # Allow multiline assignments to be cuddled. Default is true.
    allow-multiline-assign: true
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: true
    # Allow trailing comments in ending of blocks
    allow-trailing-comment: false
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0
    # Force cuddling of err checks with err var assignment
    force-err-cuddling: false
    # Allow leading comments to be separated with empty liens
    allow-separated-leading-comment: false
  gofumpt:
    # Choose whether to use the extra rules that are disabled
    # by default
    extra-rules: false

  # The custom section can be used to define linter plugins to be loaded at runtime. See README doc
  #  for more info.
  custom:
  # Each custom linter should have a unique name.
  #example:
  # The path to the plugin *.so. Can be absolute or local. Required for each custom linter
  #path: /path/to/example.so
  # The description of the linter. Optional, just for documentation purposes.
  #description: This is an example usage of a plugin linter.
  # Intended to point to the repo location of the linter. Optional, just for documentation purposes.
  #original-url: github.com/golangci/example-linter

linters:
  enable:
    - megacheck
    - govet
    - gofmt
    - gosec
    - bodyclose
    - revive
    - unconvert
    - misspell
    - dogsled
    - prealloc
    - exportloopref
    - exhaustive
    - sqlclosecheck
    - nolintlint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - unused
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goheader
    - gosmopolitan
    - inamedparam
    - makezero
    - mirror
    - misspell
    - musttag
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - wastedassign
    #- perfsprint - this needs more fixes to full use
    #- goconst # Turned this off - tons of false positives
  disable:
    - gocritic # use this for very opinionated linting
    - gci # issues a lot with import sorting
    - gochecknoglobals # this project uses some globals
    - godot # some comments do not end in a period
    - godox # finds all the HACKs
    - goerr113 # requires a lot of fixes for errors with wrapping
    - gomnd # we have too many raw numbers that are not magic
    - gomoddirectives # we use replace as needed
    - nilnil # we do not conform to this
  disable-all: false
  presets:
    - bugs
    - unused
  fast: false

issues:
  # List of regexps of issue texts to exclude, empty list by default.
  # But independently of this option we use default exclude patterns,
  # it can be disabled by `exclude-use-default: false`. To list all
  # excluded by default patterns execute `golangci-lint run --help`
  exclude:
    - abcdef

  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo

    # Exclude known linters from partially hard-vendored code,
    # which is impossible to exclude via "nolint" comments.
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec

    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1019:"

    # Exclude some gosec messages
    - linters:
        - gosec
      text: "G202:"

    # Exclude some scopelint messages
    - linters:
        - scopelint
      text: "Using the variable on range scope"

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

  # Independently of option `exclude` we use default exclude patterns,
  # it can be disabled by this option. To list all
  # excluded by default patterns execute `golangci-lint run --help`.
  # Default value for this option is true.
  exclude-use-default: false

  # The default value is false. If set to true exclude and exclude-rules
  # regular expressions become case-sensitive.
  exclude-case-sensitive: false

  # The list of IDs of default excludes to include or disable. By default, it's empty.
  include:
    - EXC0002 # disable excluding of issues about comments from golint

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # Show only new issues: if there are unstaged changes or untracked files,
  # only those changes are analyzed, else only changes in HEAD~ are analyzed.
  # It's a super-useful option for integration of golangci-lint into existing
  # large codebase. It's not practical to fix all existing issues at the moment
  # of integration: much better don't allow issues in new code.
  # Default is false.
  new: false

  # Show only new issues created after git revision `REV`
  new-from-rev: ""

  # Show only new issues created in git patch with set file path.
  #new-from-patch: path/to/patch/file

severity:
  # Default value is empty string.
  # Set the default severity for issues. If severity rules are defined, and the issues
  # do not match or no severity is provided to the rule this will be the default
  # severity applied. Severities should match the supported severity names of the
  # selected out format.
  # - Code climate: https://docs.codeclimate.com/docs/issues#issue-severity
  # -   Checkstyle: https://checkstyle.sourceforge.io/property_types.html#severity
  # -       Github: https://help.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-error-message
  default-severity: error

  # The default value is false.
  # If set to true severity-rules regular expressions become case-sensitive.
  case-sensitive: false

  # Default value is empty list.
  # When a list of severity rules are provided, severity information will be added to lint
  # issues. Severity rules have the same filtering capability as exclude rules except you
  # are allowed to specify one matcher per severity rule.
  # Only affects out formats that support setting severity information.
  rules:
    - linters:
        - dupl
      severity: info
```

</details>

### Go environment

<details>

```console
$ go version && go env

go version go1.22.1 darwin/arm64
GO111MODULE='on'
GOARCH='arm64'
GOBIN=''
GOCACHE='/Users/mrz/Library/Caches/go-build'
GOENV='/Users/mrz/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/mrz/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/mrz/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.22.1/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.22.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.22.1'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD='/Users/mrz/projects/reach/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/j1/_2pg_9l51_56g5ykwl7670wr0000gn/T/go-build1543908479=/tmp/go-build -gno-record-gcc-switches -fno-common'

```

</details>

### Verbose output of running

<details>

```console
Running golangci-lint...
INFO [config_reader] Config search paths: [./ /Users/mrz/projects/reach /Users/mrz/projects /Users/mrz /Users /] 
INFO [config_reader] Used config file .golangci.yml 
WARN [config_reader] The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`. 
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`. 
WARN [config_reader] The configuration option `output.format` is deprecated, please use `output.formats` 
WARN [config_reader] The configuration option `govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`. 
INFO [lintersdb] Active 50 linters: [asasalint asciicheck bidichk bodyclose containedctx contextcheck dogsled durationcheck errcheck errchkjson errname errorlint exhaustive exportloopref forbidigo gocheckcompilerdirectives gochecknoinits gochecksumtype gofmt goheader gosec gosimple gosmopolitan govet inamedparam ineffassign loggercheck makezero mirror misspell musttag nilerr noctx nolintlint nosprintfhostport prealloc predeclared protogetter reassign revive rowserrcheck spancheck sqlclosecheck staticcheck testifylint unconvert unparam unused wastedassign zerologlint] 
INFO [lintersdb] Active presets: [bugs unused]    
INFO [loader] Using build tags: [mytag]           
INFO [loader] Go packages loading at mode 575 (compiled_files|deps|exports_file|name|types_sizes|files|imports) took 811.25825ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 44.01775ms 
INFO [linters_context/goanalysis] analyzers took 6.156551661s with top 10 stages: the_only_name: 835.3155ms, buildir: 257.033129ms, gosec: 175.910666ms, wastedassign: 162.39925ms, ctrlflow: 141.134292ms, gofmt: 137.38875ms, SA1012: 133.173ms, unconvert: 132.805125ms, S1000: 131.612334ms, nilfunc: 131.568625ms 
WARN [runner] Can't process result by autogenerated_exclude processor: can't filter issue result.Issue{FromLinter:"contextcheck", Text:"Function `NewWriteLock$1` should pass the context parameter", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0x140013f5080), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""}: no file path for issue 
WARN [runner] Can't process result by nolint processor: can't filter issue result.Issue{FromLinter:"contextcheck", Text:"Function `NewWriteLock$1` should pass the context parameter", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0x140013f5080), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""}: no file path for issue 
WARN [runner/source_code] Failed to get line 0 for file : failed to get file  lines cache: can't get file  bytes from cache: can't read file : open : no such file or directory 
INFO [runner] Issues before processing: 114, after processing: 39 
INFO [runner] Processors filtering stat (out/in): skip_dirs: 114/114, exclude-rules: 78/114, uniq_by_line: 39/78, path_prefixer: 39/39, diff: 39/39, max_from_linter: 39/39, fixer: 39/39, sort_results: 39/39, path_prettifier: 114/114, skip_files: 114/114, exclude: 114/114, max_same_issues: 39/39, path_shortener: 39/39, severity-rules: 39/39, cgo: 114/114, filename_unadjuster: 114/114, identifier_marker: 114/114, max_per_file_from_linter: 39/39, source_code: 39/39 
INFO [runner] processing took 4.311757ms with stages: identifier_marker: 1.010501ms, source_code: 920.292µs, path_prettifier: 832.167µs, nolint: 571.875µs, exclude-rules: 395.334µs, autogenerated_exclude: 220.375µs, exclude: 111.416µs, skip_dirs: 108.751µs, skip_files: 88.751µs, cgo: 16.708µs, uniq_by_line: 15.334µs, filename_unadjuster: 11.667µs, max_per_file_from_linter: 2.833µs, path_shortener: 2.375µs, severity-rules: 2.209µs, max_same_issues: 334ns, fixer: 251ns, sort_results: 250ns, diff: 167ns, path_prefixer: 84ns, max_from_linter: 83ns 
INFO [runner] linters took 1.145263625s with stages: goanalysis_metalinter: 1.140847416s 
app/models/model/model_definitions.go:35:2: G101: Potential hardcoded credentials (gosec)
        NameSinCreditCode                   Name = "sin_credit_code"                     //nolint:gosec // SinCreditCode is the code representing a sin credit code
        ^
app/models/model/model_definitions.go:70:2: G101: Potential hardcoded credentials (gosec)
        TableSinCreditCodes                  = "sin_credit_codes"                    //nolint:gosec // TableSinCreditCodes is the sinch credit code table
        ^
app/stonehenge/client.go:67:58: G402: TLS InsecureSkipVerify set true. (gosec)
                TLSClientConfig:       &tls.Config{InsecureSkipVerify: true}, //nolint:gosec // This is temp // todo: remove this once the SSL cert issue is fixed
  
app/config/ftp.go:50:19: G304: Potential file inclusion via variable (gosec)
        contents, err := os.ReadFile(filePath) //nolint:gosec // This is a local file
                                                
```

</details>

### A minimal reproducible example or link to a public repository

<details>

```go
// UploadFileToFTP uploads a file to an FTP server
func UploadFileToFTP(client *ftp.ServerConn, filePath, targetPath string) error {

	contents, err := os.ReadFile(filePath) //nolint:gosec // This is a local file
	if err != nil {
		logger.Data(2, logger.DEBUG, fmt.Sprintf("read file error: %s", err.Error()))
		return err
	}

	return client.Stor(targetPath, bytes.NewBuffer(contents))
}
```

</details>

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### PR DESCRIPTION
**Pull request by ldez**
Before:

```console
$ golangci-lint run 
WARN [runner] Can't process result by autogenerated_exclude processor: can't filter issue result.Issue{FromLinter:"contextcheck", Text:"Function `NewWriteLock$1` should pass the context parameter", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0xc00012c480), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""}: no file path for issue 
WARN [runner] Can't process result by nolint processor: can't filter issue result.Issue{FromLinter:"contextcheck", Text:"Function `NewWriteLock$1` should pass the context parameter", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0xc00012c480), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""}: no file path for issue 
WARN [runner/source_code] Failed to get line 0 for file : failed to get file  lines cache: can't get file  bytes from cache: can't read file : open : no such file or directory 
:0: Function `NewWriteLock$1` should pass the context parameter (contextcheck)
```

With this PR:
```console
$ ./golangci-lint run
WARN [runner/invalid_issue] no file path for the issue: probably a bug inside the linter "contextcheck": &result.Issue{FromLinter:"contextcheck", Text:"Function `NewWriteLock$1` should pass the context parameter", Severity:"", SourceLines:[]string(nil), Replacement:(*result.Replacement)(nil), Pkg:(*packages.Package)(0xc000be4480), LineRange:(*result.Range)(nil), Pos:token.Position{Filename:"", Offset:0, Line:0, Column:0}, HunkPos:0, ExpectNoLint:false, ExpectedNoLintLinter:""}
```

The previous behavior was causing a side effect on the `Nolint` processor.

**EDIT:** the invalid issues reported by `contextcheck` will not produce a warning because it's a known bug. 

Fixes #4550

---

_Sponsoring is a good way to sustain open source maintainers: [sponsor me](https://github.com/sponsors/ldez)_

### CODE REVIEW

File: pkg/result/processors/invalid_issue.go [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+func (p InvalidIssue) shouldPassIssue(issue *result.Issue) (bool, error) {
+	if issue.FromLinter == "typecheck" {
+		return true, nil
+	}
+
+	if issue.FilePath() == "" {
+		// contextcheck has a known bug https://github.com/kkHAIKE/contextcheck/issues/21
+		if issue.FromLinter != "contextcheck" {
+			p.log.Warnf("no file path for the issue: probably a bug inside the linter %q: %#v", issue.FromLinter, issue)
```
Comment (alexandear) [inline pkg/result/processors/invalid_issue.go:38]: Perhaps we should show this message as Info, as there is nothing the user can do in this situation.

**Review by alexandear — APPROVED** [review]

File: pkg/result/processors/invalid_issue.go (hunk 1 above)
Comment (ldez) [reply pkg/result/processors/invalid_issue.go:38]: They can report the issue.

**Comment by ldez** [comment]
For the details:
Previously inside the `AutogeneratedExclude` processor, this `issue.FilePath() == ""` was evaluated after this `filepath.Ext(name) == ".go"` but it's impossible for a file path to be `xx.go` and empty at the same time.

When I added the new option for the `AutogeneratedExclude` processor, I fixed the behavior.

The problem is that the `AutogeneratedExclude` processor was excluding reports not related to generated files.

And so welcome to side effects.
