### PR TITLE
fix: fallback on unknown severities for code climate

### LINKED ISSUE #5349: Invalid severity type for Code Climate export format
### Welcome

- [x] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/welcome/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone [linter](https://golangci-lint.run/usage/linters/) if available (e.g., gocritic, go vet, etc.).
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### Description of the problem

Using the `code-climate` export format, there may be instances where the exported file does not have the correct severity type as defined by the [Code Climate severity types](https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types):

```json
[
  {
    "description": "gosec: G114: Use of net/http serve function that has no support for setting timeouts",
    "check_name": "gosec",
    "severity": "medium",
    "fingerprint": "4909C824372D1A973F00BF10084672E6",
    "location": { "path": "http.go", "lines": { "begin": 22 } }
  },
  {
    "description": "revive: unused-parameter: parameter 'r' seems to be unused, consider removing or renaming it as _",
    "check_name": "revive",
    "severity": "warning",
    "fingerprint": "D93243590B7D6E9AACE104BCD6F2737B",
    "location": { "path": "http.go", "lines": { "begin": 12 } }
  }
]
```

Looking at [Code Climate printer](https://github.com/golangci/golangci-lint/blob/0b0cc0e3ba8053fc61fa100d6eacbdd327152cc7/pkg/printers/codeclimate.go#L52) in the code base, it seems that the severity is emitted as-is when in fact there may be some mapping we could have done.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.63.4 built with go1.23.2 from (unknown, modified: ?, mod sum: \"h1:bJQFQ3hSfUto597dkL7ipDzOxsGEpiWdLiZ359OWOBI=\") on (unknown)
```

</details>

### Configuration

<details>

```console
$ golangci-lint run --verbose --print-issued-lines=false --out-format code-climate:golangci-lint.json,line-number
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.23.2 linux/amd64
```

</details>

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

### PR DESCRIPTION
**Pull request by ldez**
Keeps only supported severity names: https://github.com/codeclimate/platform/blob/master/spec/analyzers/SPEC.md#data-types

Closes #5349

### CODE REVIEW

File: pkg/printers/codeclimate.go [hunk 1]
```diff
@@ -48,7 +54,7 @@ func (p CodeClimate) Print(issues []result.Issue) error {
 		codeClimateIssue.Fingerprint = issue.Fingerprint()
 		codeClimateIssue.Severity = defaultCodeClimateSeverity
 
-		if issue.Severity != "" {
+		if issue.Severity != "" && slices.Contains(p.allowedSeverities, issue.Severity) {
```
Comment (ccoVeille) [inline pkg/printers/codeclimate.go:57]: It's up to you but this is enough


```suggestion
		if slices.Contains(p.allowedSeverities, issue.Severity) {
```


https://go.dev/play/p/7saiasJ_VB8

**Review by alexandear — APPROVED** [review]
