### PR TITLE
fix(custom): filter env vars when cloning the repository

### LINKED ISSUE #6513: golangci-lint custom corrupts git index when run inside a pre-commit hook (inherited GIT_INDEX_FILE)
### Welcome

- [x] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/docs/welcome/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone [linter](https://golangci-lint.run/docs/linters/) if available (e.g., gocritic, go vet, etc.).
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### How did you install golangci-lint?

Other

### Description of the problem

When `golangci-lint custom` is invoked inside a git pre-commit hook, the `git clone` it runs internally (in `pkg/commands/internal/builder.go`) **overwrites the repository's git index**, silently destroying all staged changes.

  ### Root cause

  During `git commit`, git sets `GIT_INDEX_FILE` (and `GIT_DIR`, `GIT_WORK_TREE`, etc.) as environment variables for hook subprocesses. The `clone()` method in `builder.go` uses `exec.CommandContext` without setting `cmd.Env`, so the child `git clone` process inherits these variables. The clone's internal checkout then
   writes its index to `GIT_INDEX_FILE` — which points to the **original repository's index file** — overwriting it with golangci-lint's file tree.

  After this:
  - All staged changes are permanently lost
  - `git fsck` reports dozens of "missing blob" errors (the index references objects from the golangci-lint repo, not the user's repo)
  - `git ls-files` shows golangci-lint's files (`.github/peril/`, `cmd/golangci-lint/main.go`, etc.) instead of the project's files

  The corruption is completely silent — `golangci-lint custom` exits successfully.

  ### Why it's intermittent

  `golangci-lint custom` only runs `git clone` when rebuilding the binary. If the binary already exists and matches the expected version, the clone is skipped. This means **the first commit in a new worktree** (where the custom binary doesn't exist yet) triggers the bug. Version bumps in `.custom-gcl.yml` also trigger
  it.

  The same `exec.CommandContext` pattern without `cmd.Env` exists in `goGet()`, `addReplaceDirective()`, `goModTidy()`, and `goBuild()` — those are also affected since `go get`/`go mod tidy` can invoke git internally.

  ### Note on "tried with standalone linter"

  This is not a linter analysis bug — it's a bug in the `golangci-lint custom` build command's subprocess environment handling.

  ### Suggested fix

  Set `cmd.Env` on all `exec.CommandContext` calls in `builder.go`, filtering out `GIT_DIR`, `GIT_INDEX_FILE`, `GIT_WORK_TREE`, and other repo-state variables while preserving transport/auth variables like `GIT_SSH_COMMAND` and `GIT_EXEC_PATH`. This is the same approach pre-commit uses internally
  ([`no_git_env()`](https://github.com/pre-commit/pre-commit/blob/main/pre_commit/git.py#L27)).

  I have a fix ready and will open a PR.

### Version of golangci-lint

  ```console
  golangci-lint has version 2.11.4 built with go1.26.1 from 8f3b0c7e on 2026-03-22T17:35:14Z
  ```

### Configuration

 ```yaml
  # .custom-gcl.yml
  version: v2.11.4
  plugins:
    - module: "go.uber.org/nilaway"
      import: "go.uber.org/nilaway/cmd/gclplugin"
      version: v0.0.0-20260318203545-ad240b12fb4c
  ```

  ```yaml
  # Relevant .pre-commit-config.yaml hook entry
  - id: golangci-lint-nilaway
    name: golangci-lint (with nilaway)
    entry: bash -c '... golangci-lint custom ... && ./custom-gcl run'
    language: system
    pass_filenames: false
    types: [go]
  ```

### Go environment

<details>

```console
  $ go version && go env
  go version go1.26.2 darwin/arm64
  AR='ar'
  CC='clang'
  CGO_CFLAGS='-O2 -g'
  CGO_CPPFLAGS=''
  CGO_CXXFLAGS='-O2 -g'
  CGO_ENABLED='1'
  CGO_FFLAGS='-O2 -g'
  CGO_LDFLAGS='-O2 -g'
  CXX='clang++'
  GCCGO='gccgo'
  GO111MODULE='on'
  GOARCH='arm64'
  GOARM64='v8.0'
  GOAUTH='netrc'
  GOBIN='/Users/mocull/go/bin'
  GOCACHE='/Users/mocull/Library/Caches/go-build'
  GOCACHEPROG=''
  GODEBUG=''
  GOENV='/Users/mocull/Library/Application Support/go/env'
  GOEXE=''
  GOEXPERIMENT=''
  GOFIPS140='off'
  GOFLAGS=''
  GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/jh/7wmdw3ys1zd_0462x_mz25d00000gn/T/go-build2221269596=/tmp/go-build -gno-record-gcc-switches -fno-common'
  GOHOSTARCH='arm64'
  GOHOSTOS='darwin'
  GOINSECURE=''
  GOMOD='/Users/mocull/entegrata/_workspaces/mapping-alfa/go.mod'
  GOMODCACHE='/Users/mocull/go/pkg/mod'
  GONOPROXY='github.com/Entegrata,buf.build'
  GONOSUMDB='github.com/Entegrata,buf.build'
  GOOS='darwin'
  GOPATH='/Users/mocull/go'
  GOPRIVATE='github.com/Entegrata,buf.build'
  GOPROXY='https://proxy.golang.org,direct'
  GOROOT='/Users/mocull/.local/share/mise/installs/go/1.26.2'
  GOSUMDB='sum.golang.org'
  GOTELEMETRY='local'
  GOTELEMETRYDIR='/Users/mocull/Library/Application Support/go/telemetry'
  GOTMPDIR=''
  GOTOOLCHAIN='auto'
  GOTOOLDIR='/Users/mocull/.local/share/mise/installs/go/1.26.2/pkg/tool/darwin_arm64'
  GOVCS=''
  GOVERSION='go1.26.2'
  GOWORK=''
  PKG_CONFIG='pkg-config'
```

</details>

### Verbose output of running

<details>

 ```console
  # The bug is in `golangci-lint custom`, not `golangci-lint run`.
  # When run inside a git hook environment, `golangci-lint custom` exits
  # successfully but silently corrupts the git index.

  # Before:
  $ git ls-files | wc -l
  875

  # Simulating the pre-commit hook environment:
  $ export GIT_INDEX_FILE="$(git rev-parse --git-dir)/index"
  $ export GIT_DIR="$(git rev-parse --git-dir)"
  $ golangci-lint custom
  # (exits 0, no errors)

  # After:
  $ git ls-files | wc -l
  1823
  $ git ls-files | head -5
  .custom-gcl.reference.yml
  .gitattributes
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  # ^^^ These are golangci-lint's files, not the project's files.
  ```

</details>

### A minimal reproducible example or link to a public repository

<details>

```bash
#!/bin/bash
# Reproduces golangci-lint custom overwriting the git index
# via inherited GIT_INDEX_FILE from the hook environment.
#
# Prerequisites: go, git, golangci-lint (v2.x) on PATH.
set -euo pipefail

WORK=/tmp/gcl-index-bug-repro
rm -rf "$WORK"
mkdir -p "$WORK"
cd "$WORK"

# Set up a minimal git repo with a Go module
git init repo && cd repo
go mod init example.com/repro
git add .
git commit -m "init"

# Create the custom-gcl config
cat >.custom-gcl.yml <<'EOF'
version: v2.11.4
plugins:
  - module: "go.uber.org/nilaway"
    import: "go.uber.org/nilaway/cmd/gclplugin"
    version: v0.0.0-20260318203545-ad240b12fb4c
EOF

# Stage a file so we can observe it getting lost
echo "package main" >main.go
git add .

echo "=== Index BEFORE (expect .custom-gcl.yml, go.mod, main.go) ==="
git ls-files

# Simulate the environment git sets during pre-commit hook execution.
# git always uses absolute paths for these variables in hooks.
export GIT_INDEX_FILE="$(git rev-parse --absolute-git-dir)/index"
export GIT_DIR="$(git rev-parse --absolute-git-dir)"

# This is the bug: golangci-lint custom's git clone writes
# golangci-lint's index to GIT_INDEX_FILE
golangci-lint custom

echo ""
AFTER_COUNT=$(git ls-files | wc -l | tr -d ' ')
echo "=== Index AFTER ==="
echo "Expected: same 3 files as before"
echo "Actual:   $AFTER_COUNT files — the index was overwritten with golangci-lint's repo tree"
echo ""
echo "First 10 files now in the index (none of these are ours):"
git ls-files | head -10 || true

echo ""
if git ls-files | grep -q "main.go"; then
    echo "PASS: main.go still in index"
else
    echo "FAIL: main.go is gone — all staged changes silently destroyed"
    echo ""
    echo "git diff now fails because the index references objects from golangci-lint's repo:"
    git diff 2>&1 | head -3 || true
    echo ""
    echo "The repo at $WORK/repo is left intact for inspection."
fi
```

</details>

### Validation

- [x] Yes, I've included all the information above (example, version, config, etc.).

### Supporter

- [ ] I am a [sponsor/backer](https://donate.golangci.org) of this project.

### PR DESCRIPTION
**Pull request by ldez**
Fixes #6513

### CODE REVIEW

File: pkg/commands/internal/builder_test.go [hunk 1]
```diff
@@ -54,3 +55,52 @@ func Test_sanitizeVersion(t *testing.T) {
 		})
 	}
 }
+
+func Test_filterEnviron(t *testing.T) {
```
Comment (Maxattax97) [inline pkg/commands/internal/builder_test.go]: I like your tests better than mine, good job!

File: pkg/commands/internal/builder.go [hunk 2]
```diff
@@ -96,6 +96,7 @@ func (b Builder) clone(ctx context.Context) error {
 		"https://github.com/golangci/golangci-lint.git",
 	)
 	cmd.Dir = b.root
+	cmd.Env = filterGitEnviron(os.Environ())
```
Comment (Maxattax97) [inline pkg/commands/internal/builder.go:99]: It's a keen observation that technically it is only strictly necessary to filter the env for this clone path. Good thinking.

**Review by Maxattax97 — COMMENTED** [review]
✅  Appreciate the quick turnaround 🙏

File: pkg/commands/internal/builder_test.go [hunk 3]
```diff
@@ -54,3 +55,52 @@ func Test_sanitizeVersion(t *testing.T) {
...
+		"GIT_CONFIG_VALUE_1=bot@example.com",
+		"GIT_EXEC_PATH=/usr/lib/git-core",
+		"GIT_HTTP_PROXY_AUTHMETHOD=basic",
+		"GIT_SSH=/usr/bin/ssh",
+		"GIT_SSH_COMMAND=ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no",
+		"GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt",
+		"GIT_SSL_NO_VERIFY=true",
+	}
+
+	assert.Equal(t, expected, envs)
```
Comment (alexandear) [inline pkg/commands/internal/builder_test.go:102]: We can change to [ElementsMatch](https://pkg.go.dev/github.com/stretchr/testify/assert#ElementsMatch):
```suggestion
	assert.ElementsMatch(t, expected, envs)
```

and remove `slices.Sort`.

File: pkg/commands/internal/builder.go [hunk 4]
```diff
@@ -280,3 +281,35 @@ func sanitizeVersion(v string) string {
...
+
+		switch key {
+		case "GIT_EXEC_PATH", "GIT_SSH", "GIT_SSH_COMMAND", "GIT_SSL_CAINFO",
+			"GIT_SSL_NO_VERIFY", "GIT_CONFIG_COUNT",
+			"GIT_HTTP_PROXY_AUTHMETHOD",
+			"GIT_ALLOW_PROTOCOL",
+			"GIT_ASKPASS":
+			filtered = append(filtered, env)
+		default:
+			continue
```
Comment (alexandear) [inline pkg/commands/internal/builder.go]: nit: redundant `continue`

**Review by alexandear — APPROVED** [review]
