### PR TITLE
Return error if any linter fails to run

### LINKED ISSUE #2357: Run returns 0 on build failure
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

I noticed while looking at the CI logs of the following PR that `golangci-lint run` was returning with an exit code of `0`, although the code doesn't compile: https://github.com/triggermesh/triggermesh/pull/263

I can see the following warning in the logs:

```
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package cortex: could not load export data: no export data for "go.opentelemetry.io/contrib/exporters/metric/cortex"
```

The dependency that fails to build is indeed the one I expected, but the outcome and the message are surprising to me.
My reasoning is that:

1. If such failure occurs, it's unlikely that the code can be considered acceptable.
1. If I see this message in isolation from the change, I'm unlikely to be able to determine where the linter failed, and why.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.43.0 built from (unknown, mod sum: "h1:SLwZFEmDgopqZpfP495zCtV9REUf551JJlJ51Ql7NZA=") on (unknown)
```

</details>

### Configuration file

<details>

```yaml
linters:
  enable:
  - gofmt
  - stylecheck

run:
  timeout: 10m
```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.17.2 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/acotten/.cache/go-build"
GOENV="/home/acotten/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/acotten/go/pkg/mod"
GONOPROXY="github.com/triggermesh/*"
GONOSUMDB="github.com/triggermesh/*"
GOOS="linux"
GOPATH="/home/acotten/go"
GOPRIVATE="github.com/triggermesh/*"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.2"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/acotten/go/src/github.com/triggermesh/triggermesh/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2177709345=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ golangci-lint run -v
INFO [config_reader] Config search paths: [./ /home/acotten/go/src/github.com/triggermesh/triggermesh /home/acotten/go/src/github.com/triggermesh /home/acotten/go/src/github.com /home/acotten/go/src /home/acotten/go /home/acotten /home /]
INFO [config_reader] Used config file .golangci.yaml
INFO [lintersdb] Active 12 linters: [deadcode errcheck gofmt gosimple govet ineffassign staticcheck structcheck stylecheck typecheck unused varcheck]
INFO [loader] Go packages loading at mode 575 (deps|exports_file|compiled_files|files|imports|name|types_sizes) took 2.9607695s
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 94.7101ms
INFO [linters context/goanalysis] analyzers took 9m18.8387247s with top 10 stages: buildir: 6m32.1698428s, nilness: 48.5924902s, typedness: 6.8536132s, inspect: 4.6726596s, fact_deprecated: 4.2246186s, gofmt: 3.88425s, fact_purity: 3.8326054s, ctrlflow: 3.3801925s, printf: 3.1457179s, unused: 2.4407979s
WARN [runner] Can't run linter goanalysis_metalinter: buildir: failed to load package cortex: could not load export data: no export data for "go.opentelemetry.io/contrib/exporters/metric/cortex"
INFO [runner] processing took 4.9µs with stages: max_same_issues: 1.1µs, nolint: 500ns, skip_dirs: 500ns, autogenerated_exclude: 300ns, filename_unadjuster: 300ns, identifier_marker: 300ns, cgo: 300ns, max_from_linter: 200ns, exclude: 200ns, skip_files: 200ns, path_prettifier: 200ns, diff: 100ns, source_code: 100ns, path_prefixer: 100ns, uniq_by_line: 100ns, exclude-rules: 100ns, max_per_file_from_linter: 100ns, sort_results: 100ns, path_shortener: 100ns, severity-rules: 0s
INFO [runner] linters took 1m9.6487956s with stages: goanalysis_metalinter: 1m9.6485264s
INFO File cache stats: 0 entries of total size 0B
INFO Memory: 524 samples, avg is 2190.5MB, max is 2950.1MB
INFO Execution took 1m12.7177277s
```

</details>

### Code example or link to a public repository

<details>

See aforementioned PR.

The error is in this specific package:

https://github.com/triggermesh/triggermesh/tree/dependabot/go_modules/go.opentelemetry.io/otel/sdk/metric-0.25.0/pkg/targets/adapter/opentelemetrytarget

</details>

### PR DESCRIPTION
**Pull request by bombsimon**
If a linter fails, store its name and use that to create a list of all linters that failed to run.
This will make `golangci-lint` exit with a non-zero exit code if one or more linters fails but still ensure all linters are run before exiting.

Fixes #2357

### CODE REVIEW

File: pkg/lint/runner.go [hunk 1]
```diff
@@ -192,20 +192,34 @@ func (r Runner) Run(ctx context.Context, linters []*linter.Config, lintCtx *lint
...
 			}
 			issues = append(issues, linterIssues...)
 		})
 	}
 
-	return r.processLintResults(issues), nil
+	if len(failedLinters) > 0 {
+		linterErr = fmt.Errorf(
+			"one or more linters failed to run: %s",
+			strings.Join(failedLinters, ", "),
```
Comment (butuzov) [inline pkg/lint/runner.go:218]: Only nit: Do we really need fmt (formatting string here)?

Comment (bombsimon) [reply pkg/lint/runner.go:218]: I think it's more readable and pretty common with errors I think since 1.13 when `%w` became the de facto standard for wrapping errors. This isn't wrapping though so I guess string concatenation is the alternative you're looking for?

```go
linterErr = errors.New("one or more linters failed to run: " + strings.Join(failedLinters, ", ")
```

Comment (butuzov) [reply pkg/lint/runner.go:218]: Yeah, pretty much it is!

Comment (bombsimon) [reply pkg/lint/runner.go]: I don't feel super strong about it so I'll push a change!

**Comment by bombsimon** [comment]
@ldez Wanna hear your thoughts on this since you rejected #2410, WDYT?

**Review by butuzov — APPROVED** [review]
Last word by @ldez

File: pkg/lint/runner.go [hunk 2]
```diff
@@ -192,20 +192,31 @@ func (r Runner) Run(ctx context.Context, linters []*linter.Config, lintCtx *lint
 	sw := timeutils.NewStopwatch("linters", r.Log)
 	defer sw.Print()
 
-	var issues []result.Issue
+	var (
+		linterErr     error
+		failedLinters []string
+		issues        []result.Issue
+	)
+
```
Comment (ldez) [inline pkg/lint/runner.go:200]:
```suggestion

	var e *multierror.Error

```

File: pkg/lint/runner.go [hunk 3]
```diff
@@ -192,20 +192,31 @@ func (r Runner) Run(ctx context.Context, linters []*linter.Config, lintCtx *lint
...
 	for _, lc := range linters {
 		lc := lc
 		sw.TrackStage(lc.Name(), func() {
 			linterIssues, err := r.runLinterSafe(ctx, lintCtx, lc)
 			if err != nil {
+				failedLinters = append(failedLinters, lc.Linter.Name())
```
Comment (ldez) [inline pkg/lint/runner.go:206]:
```suggestion
				e = multierror.Append(e, fmt.Errorf("can't run linter %s: %w", lc.Linter.Name(), err))
```

File: pkg/lint/runner.go [hunk 4]
```diff
@@ -192,20 +192,31 @@ func (r Runner) Run(ctx context.Context, linters []*linter.Config, lintCtx *lint
...
 			issues = append(issues, linterIssues...)
 		})
 	}
 
-	return r.processLintResults(issues), nil
+	if len(failedLinters) > 0 {
+		linterErr = errors.New("one or more linters failed to run: " + strings.Join(failedLinters, ", "))
+	}
+
+	return r.processLintResults(issues), linterErr
```
Comment (ldez) [inline pkg/lint/runner.go:219]:
```suggestion
	return r.processLintResults(issues), e.ErrorOrNil()
```

**Review by ldez — CHANGES_REQUESTED** [review]

**Comment by ldez** [comment]
It's better but it's still not as "expected": if a linter fails, the issues will not be displayed.

I'm not sure about what we really expect :thinking:

**Comment by bombsimon** [comment]
Can a linter fail without it being a compilation issue? I know it theoretically can, but have we seen that reported? My experience is that this is caused by compilation issues (e.g faulty `go.mod/sum`) the majority of times and when that happens I think this is the expected behavior and that it makes sense that no issues are reported from that linter.

Either way the only actual difference this change adds is a non-zero exit code which I think makes sense if a linter fails, no matter the reason.

What is it that blocks this change? I'm pretty sure this used to be the behavior regarding the exit code so I don't think we need to wait for 2.0 to make this change.

**Comment by ldez** [comment]
In fact, I have a solution but I don't like it :smile:

So I will approve, but I'm still thinking there is a design flaw behind this code section (not related to your PR).

**Review by ldez — APPROVED** [review]
