### PR TITLE
plugin: temporarily hide warning about using plugins using the old API

### LINKED ISSUE #4001: v1.54.0 warns about using plugins using the old API
### Welcome

- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've read the typecheck section of the FAQ (https://golangci-lint.run/usage/faq/#why-do-you-have-typecheck-errors).
- [X] Yes, I've tried with the standalone linter if available (e.g., gocritic, go vet, etc.). (https://golangci-lint.run/usage/linters/)

### Description of the problem

In Kubernetes we need to update golangci-lint to 1.54.0 to support Go 1.21 and also need to backport that update to older release branches, ideally without any other unnecessary changes. Older branches have to be updated to stay on a supported Go release. In particular we would prefer to not update the version of logcheck, the custom plugin that Kubernetes is using.

This currently leads to this warning on every invocation, which happens multiple times for different modules:

     ERROR: level=warning msg="plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: https://golangci-lint.run/contributing/new-linters/#create-a-plugin"
     
It would be nice to give users a bit more time to upgrade plugins before warning about them. Can this warning be removed from v1.54.x and be enabled again in 1.55.x?

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version v1.54.0 built with go1.21.0 from (unknown, mod sum: "h1:sWD8sCmlWRZYj7I0VZLwX7uYfjIcIUHq8rSO4IJtzdw=") on (unknown)
```
</details>

### Configuration

<details>

https://github.com/kubernetes/kubernetes/blob/18c3c7efb3bcccd84cccc7dacc01f0a7427b8eb9/hack/golangci.yaml#L1-L60

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.21.0 linux/amd64
GO111MODULE=''
GOARCH='amd64'
GOBIN=''
GOCACHE='/home/pohly/.cache/go-build'
GOENV='/home/pohly/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/nvme/gopath/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/nvme/gopath'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/nvme/gopath/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.21.0.linux.amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/nvme/gopath/src/k8s.io/kubernetes/_output/local/.gimme/versions/go1.21.0.linux.amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.0'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/nvme/gopath/src/k8s.io/kubernetes/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1184767112=/tmp/go-build -gno-record-gcc-switches'
```

</details>

### Verbose output of running

<details>

```console
$ kubernetes$ hack/verify-golangci-lint.sh ./pkg/routes
go version go1.21.0 linux/amd64
installing golangci-lint and logcheck plugin from hack/tools into /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin
running env LOGCHECK_CONFIG=/nvme/gopath/src/k8s.io/kubernetes/hack/logcheck.conf /nvme/gopath/src/k8s.io/kubernetes/_output/local/bin/golangci-lint run --config=/nvme/gopath/src/k8s.io/kubernetes/hack/golangci.yaml --color=always ./pkg/routes
ERROR: level=warning msg="plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: https://golangci-lint.run/contributing/new-linters/#create-a-plugin"
Congratulations! All files are passing lint :-)
```

</details>

### Code example or link to a public repository

https://github.com/kubernetes/kubernetes/tree/master

### Validation

- [X] Yes, I've included all information above (version, config, etc.).

### PR DESCRIPTION
**Pull request by ldez**
Fixes #4001

I will create a PR after the merge of this one to restore the log.

### CODE REVIEW

**Review by bombsimon — COMMENTED** [review]
I agree with your comment (which I also wrote in the ticket). I don't get how waiting until the next release to display the log message would make any difference? It will just give the user less time to fix, or `golangci-lint` one extra release before fully deprecating/removing (if ever?).

**Comment by ldez** [comment]
I updated to PR based on https://github.com/golangci/golangci-lint/issues/4001#issuecomment-1674250029

@bombsimon WDYT?

File: pkg/lint/lintersdb/custom_linters.go [hunk 1]
```diff
@@ -115,8 +116,11 @@ func (m *Manager) lookupAnalyzerPlugin(plug *plugin.Plugin) ([]*analysis.Analyze
 		return nil, err
 	}
 
-	m.log.Warnf("plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: " +
-		"https://golangci-lint.run/contributing/new-linters/#create-a-plugin")
+	// TODO(ldez): remove this env var in the next minor version (v1.55.0)
+	if os.Getenv("GOLANGCI_LINT_HIDE_WARNING_ABOUT_PLUGIN_API_DEPRECATION") != "1" {
```
Comment (bombsimon) [inline pkg/lint/lintersdb/custom_linters.go:120]: Personally I think not forcing just `1` but any set value is more appropriate for environment variables and also more common.

```suggestion
	if _, ok := os. LookupEnv("GOLANGCI_LINT_HIDE_WARNING_ABOUT_PLUGIN_API_DEPRECATION"); !ok {
```

File: pkg/lint/lintersdb/custom_linters.go [hunk 2]
```diff
@@ -115,8 +116,11 @@ func (m *Manager) lookupAnalyzerPlugin(plug *plugin.Plugin) ([]*analysis.Analyze
 		return nil, err
 	}
 
-	m.log.Warnf("plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: " +
-		"https://golangci-lint.run/contributing/new-linters/#create-a-plugin")
+	// TODO(ldez): remove this env var in the next minor version (v1.55.0)
```
Comment (bombsimon) [inline pkg/lint/lintersdb/custom_linters.go:119]: You mean remove as in always show the message without support to surpress it or remove the whole log?

File: pkg/lint/lintersdb/custom_linters.go [hunk 3]
```diff
@@ -115,8 +116,11 @@ func (m *Manager) lookupAnalyzerPlugin(plug *plugin.Plugin) ([]*analysis.Analyze
...
+	if os.Getenv("GOLANGCI_LINT_HIDE_WARNING_ABOUT_PLUGIN_API_DEPRECATION") != "1" {
+		m.log.Warnf("plugin: 'AnalyzerPlugin' plugins are deprecated, please use the new plugin signature: " +
+			"https://golangci-lint.run/contributing/new-linters/#create-a-plugin")
```
Comment (bombsimon) [inline pkg/lint/lintersdb/custom_linters.go:122]: Should we add something like this in the log?
> You can hide this message by setting `GOLANGCI_LINT_HIDE_WARNING_ABOUT_PLUGIN_API_DEPRECATION`

**Review by bombsimon — APPROVED** [review]
LGTM, just some minor comments

File: pkg/lint/lintersdb/custom_linters.go (hunk 1 above)
Comment (ldez) [reply pkg/lint/lintersdb/custom_linters.go:120]: I put `1` just because it's not a real option but LookupEnv will work.

File: pkg/lint/lintersdb/custom_linters.go (hunk 3 above)
Comment (ldez) [reply pkg/lint/lintersdb/custom_linters.go:122]: For me it's not a real option, it's more of a hidden feature only for people that read the changelog :sweat_smile:

File: pkg/lint/lintersdb/custom_linters.go (hunk 2 above)
Comment (ldez) [reply pkg/lint/lintersdb/custom_linters.go]: I improved the comment
