### PR TITLE
revive: fix suggested fixes

### LINKED ISSUE #6292: Applying revive suggested fixes results in invalid go code
### Welcome

- [x] Yes, I'm using a binary release within 2 latest [releases](https://github.com/golangci/golangci-lint/releases). Only such installations are supported.
- [x] Yes, I've searched similar [issues on GitHub](https://github.com/golangci/golangci-lint/issues) and didn't find any.
- [x] Yes, I've read the `typecheck` section of the [FAQ](https://golangci-lint.run/docs/welcome/faq/#why-do-you-have-typecheck-errors).
- [x] Yes, I've tried with the standalone [linter](https://golangci-lint.run/docs/linters/) if available (e.g., gocritic, go vet, etc.).
- [x] I agree to follow this project's [Code of Conduct](https://github.com/golangci/golangci-lint?tab=coc-ov-file)

### How did you install golangci-lint?

Official binary

### Description of the problem

The `ReplacementLine` from revive does not contain an ending newline, so I would expect the golangci-lint revive linter to add it when the fix will result in an invalid go file, but it doesn't.

In addition, the golangci-lint revive linter has applied an extra tab which comes from the revive ReplacementLine.

The golangci-lint revive linter needs to ignore the column when applying the ReplacementLine, and do want says literally - replace the entire line, and then add the newline to the end.

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
golangci-lint has version 2.7.2 built with go1.25.4 from 9f61b0f5 on 2025-12-07T16:57:12Z
```

</details>

### Configuration

<details>

```yaml
version: '2'
linters:
  default: none
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: errorf

```

</details>

### Go environment

<details>

```console
$ go version && go env
go version go1.25.5 linux/amd64
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/home/jwong/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/home/jwong/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS='-buildvcs=false'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1941364073=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/home/jwong/golangci-lint-bug/go.mod'
GOMODCACHE='/home/jwong/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/jwong/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/snap/go/11017'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/jwong/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/snap/go/11017/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.25.5'
GOWORK=''
PKG_CONFIG='pkg-config'
```

</details>

### Verbose output of running

<details>

```console
$ golangci-lint cache clean
$ GO111MODULE=on golangci-lint run -v --fix main.go
INFO golangci-lint has version 2.7.2 built with go1.25.4 from 9f61b0f5 on 2025-12-07T16:57:12Z 
INFO [config_reader] Config search paths: [./ /home/jwong/golangci-lint-bug /home/jwong /home /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [config_reader] Module name "golangci-lint-bug"          
INFO maxprocs: Leaving GOMAXPROCS=20: CPU quota undefined 
INFO [goenv] Read go env for 45.820245ms: map[string]string{"GOCACHE":"/home/jwong/.cache/go-build", "GOROOT":"/snap/go/11017"} 
INFO [lintersdb] Active 1 linters: [revive]       
INFO [loader] Go packages loading at mode 8199 (name|compiled_files|files) took 129.582187ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 111.666µs 
INFO [linters_context/goanalysis] analyzers took 0s with no stages 
INFO [runner] Applying suggested fixes            
WARN [runner] (fmt) formatting file /home/jwong/golangci-lint-bug/main.go: 12:27: expected ';', found 'return' 
INFO [runner] fixer took 86.023µs with stages: all: 86.023µs 
INFO [runner] Issues before processing: 1, after processing: 0 
INFO [runner] Processors filtering stat (in/out): filename_unadjuster: 1/1, diff: 1/1, path_absoluter: 1/1, exclusion_paths: 1/1, fixer: 1/0, cgo: 1/1, invalid_issue: 1/1, path_relativity: 1/1, generated_file_filter: 1/1, exclusion_rules: 1/1, nolint_filter: 1/1 
INFO [runner] processing took 152µs with stages: fixer: 99.211µs, nolint_filter: 38.339µs, generated_file_filter: 9.087µs, path_relativity: 1.378µs, sort_results: 813ns, cgo: 427ns, invalid_issue: 408ns, filename_unadjuster: 315ns, max_same_issues: 307ns, diff: 230ns, exclusion_rules: 211ns, path_prettifier: 201ns, source_code: 191ns, exclusion_paths: 189ns, path_shortener: 166ns, path_absoluter: 162ns, uniq_by_line: 109ns, max_from_linter: 104ns, max_per_file_from_linter: 88ns, severity-rules: 64ns 
INFO [runner] linters took 570.737µs with stages: goanalysis_metalinter: 374.478µs 
0 issues.
INFO File cache stats: 1 entries of total size 139B 
INFO Memory: 3 samples, avg is 35.8MB, max is 35.8MB 
INFO Execution took 176.298803ms   
```

</details>

### A minimal reproducible example or link to a public repository

<details>

**Before**

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
}

func Bar() (int, error) {
	c := errors.New(fmt.Sprintf("test"))
	return 1, c
}

```

**After**

```go
package main

import (
	"errors"
	"fmt"
)

func main() {
}

func Bar() (int, error) {
		c := fmt.Errorf("test")	return 1, c // expected ';', found 'return'
}

```

</details>

### Validation

- [x] Yes, I've included all information above (version, config, etc.).

### Supporter

- [ ] I am a sponsor/backer through [GitHub](https://github.com/sponsors/golangci/) or [OpenCollective](https://opencollective.com/golangci-lint)

### PR DESCRIPTION
**Pull request by ldez**
Fixes #6292

### CODE REVIEW

File: pkg/golinters/revive/revive.go [hunk 1]
```diff
@@ -155,8 +155,10 @@ func (w *wrapper) toIssue(pass *analysis.Pass, failure *lint.Failure) *goanalysi
 		if failure.Filename() == f.Name() {
 			issue.SuggestedFixes = []analysis.SuggestedFix{{
 				TextEdits: []analysis.TextEdit{{
-					Pos:     f.LineStart(failure.Position.Start.Line),
-					End:     goanalysis.EndOfLinePos(f, failure.Position.End.Line),
+					Pos: f.LineStart(failure.Position.Start.Line),
```
Comment (wyuenho) [inline pkg/golinters/revive/revive.go:158]: Testing this change with my exact test case, this still produces an extra indentation. Something else is not producing the actual line start from the failure position.

Comment (ldez) [reply pkg/golinters/revive/revive.go:158]: I tested with your exact test case, and it produces no extra indentation.
