### PR TITLE
fix: exit early on run --version

### LINKED ISSUE #3066: golangci-lint run --version hangs instead of exiting
- [X] Yes, I'm using a binary release within 2 latest major releases. Only such installations are supported.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).
- [X] Yes, I've tried with the standalone linter if available. (https://golangci-lint.run/usage/linters/)

### Description of the problem

golangci-lint run --version
golangci-lint has version 1.48.0 built from 2d8fea81 on 2022-08-04T18:44:38Z

ERRO Running error: context loading failed: failed to load packages: timed out to load packages: context deadline exceeded 
ERRO Timeout exceeded: try increasing it by passing --timeout option 

As far as I can tell, this is a regression from 1.47.x

### Version of golangci-lint

<details>

```console
$ golangci-lint --version
# Paste output here
```

</details>

### Configuration file

<details>

```console
$ cat .golangci.yml
# paste output here
```

</details>

### Go environment

<details>

```console
$ go version && go env
# paste output here
go version go1.18.4 linux/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/rski/.cache/go-build"
GOENV="/home/rski/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/rski/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/rski/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/nix/store/wzq7am3816mv7vc73wq5wjh1xc2fmyim-go-1.18.4/share/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/nix/store/wzq7am3816mv7vc73wq5wjh1xc2fmyim-go-1.18.4/share/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.18.4"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/rski/Code/go/src/arista/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build2326600941=/tmp/go-build -gno-record-gcc-switches"
```

</details>

### Verbose output of running

<details>

before
```console
golangci-lint run --version -v                                                                                                                                                   
INFO [config_reader] Config search paths: [ [redacted ] ] 
golangci-lint has version 1.47.2 built from 61673b34 on 2022-07-21T10:53:45Z
```
after:
```console
golangci-lint run --version -v                                                                                                                                                   
INFO [config_reader] Config search paths:
golangci-lint has version 1.48.0 built from 2d8fea81 on 2022-08-04T18:44:38Z
INFO [lintersdb] Active 9 linters: [deadcode errcheck gosimple govet ineffassign staticcheck typecheck unused varcheck] 
```
</details>

### PR DESCRIPTION
**Pull request by ldez**
Fixes #3066

### CODE REVIEW

**Review by bombsimon — APPROVED** [review]
LGTM!

Do you know what change made the command not exit successfully after returning `nil`? Just pondering if it's worth adding some details to why we have to do this

**Comment by ldez** [comment]
> Do you know what change made the command not exit successfully after returning nil? 

It's because the version is displayed inside the preRun so a `return nil` will not stop the `run`.

File: pkg/commands/root.go [hunk 1]
```diff
@@ -12,13 +12,14 @@ import (
...
 	"github.com/golangci/golangci-lint/pkg/config"
+	"github.com/golangci/golangci-lint/pkg/exitcodes"
 	"github.com/golangci/golangci-lint/pkg/logutils"
 )
 
 func (e *Executor) persistentPreRun(_ *cobra.Command, _ []string) error {
 	if e.cfg.Run.PrintVersion {
 		_, _ = fmt.Fprintf(logutils.StdOut, "golangci-lint has version %s built from %s on %s\n", e.version, e.commit, e.date)
-		return nil
+		os.Exit(exitcodes.Success) // a return nil is not enough to stop the process because we are inside the `preRun`.
```
Comment (rski) [inline pkg/commands/root.go:22]: heh, I wondered why we did a return instead of just an exit here :)

**Review by rski — APPROVED** [review]
